# Generated by Django 4.1.7 on 2023-02-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_academicsinfo_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='salary',
            field=models.BigIntegerField(blank=True),
        ),
    ]
